; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Libraries
lib_deps = 
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/RTClib@^2.1.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    waspinator/AccelStepper@^1.64
    bblanchon/ArduinoJson@^7.0.4
    me-no-dev/ESP Async WebServer @ ^1.2.3

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Monitor settings
monitor_speed = 115200
monitor_filters = 
    colorize
    default

; Upload settings
upload_speed = 921600
