; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Libraries
lib_deps = 
    paulstoffregen/OneWire@^2.3.7
    paulstoffregen/DallasTemperature@^3.12.0
    adafruit/Adafruit SHT31 Library@^2.2.1
    adafruit/RTClib@^2.1.1
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit BusIO@^1.14.5
    bblanchon/ArduinoJson@^7.0.4
    links2004/WebSockets@^2.4.1
    Wasp8266/AccelStepper@^1.64
    br3ttb/Arduino-PID-Library@^1.2.2

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Monitor settings
monitor_speed = 115200
monitor_filters = 
    colorize
    default

; Upload settings
upload_speed = 921600
